In [10]:
# Library import

import warnings

warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

import pandas as pd
from pathlib import Path
import datetime as dt
import numpy as np


from pydataxm import *                           #Se realiza la importación de las librerias necesarias para ejecutar                        
from pydataxm.pydataxm import ReadDB as apiXM

In [11]:
# Ruta General
sRutaDesp=r'C:\Alejo\cops\Python\Utils\\'
d_Fecha='2025-05-10'
#Cambiar a formato fecha
d_Fecha=dt.datetime.strptime(d_Fecha,'%Y-%m-%d')

ano=d_Fecha.year
mes=d_Fecha.month
dia=d_Fecha.day

filetype='dDEC'

l_colGen=['Planta'] 
for i in range(1,25): 
    l_colGen.append(i)

In [12]:
folderpath=Path(sRutaDesp)
file=filetype + "{:02d}".format(mes) + "{:02d}".format(dia) + '.txt'
s_filepath=folderpath.joinpath(str(ano) + '-' + "{:02d}".format(mes),file)

df_Aux = pd.read_csv(s_filepath, sep=',',names=l_colGen,encoding="ISO-8859-1")

In [13]:
objetoAPI = pydataxm.ReadDB()                    #Se almacena el servicio en el nombre objetoAPI
df =objetoAPI.get_collections()   
FechaIni=dt.date(2025, 5, 10)
FechaFin=dt.date(2025, 5, 10)
df_Rec= apiXM.request_data(pydataxm.ReadDB(),    #Se indica el objeto que contiene el serivicio
                        "ListadoRecursos",                #Se indica el nombre de la métrica tal como se llama en el campo metricID
                        "Sistema",                 #Campo que indica si es Sistema, Agente, Recurso, Comercializador
                        FechaIni,       #Corresponde a la fecha inicial de la consulta
                        FechaFin)      #Corresponde a la fecha final de la consulta
df_Rec=df_Rec.drop('Date',axis=1)

In [14]:
df_Rec.head(5) #Se visualizan las primeras 5 filas del dataframe

,Id,Values_Code,Values_Name,Values_Type,Values_Disp,Values_RecType,Values_CompanyCode,Values_EnerSource,Values_OperStartdate,Values_State
0,Sistema,2QBW,EL POPAL,HIDRAULICA,NO DESPACHADO CENTRALMENTE,NORMAL,ISGG,AGUA,2014-03-31,OPERACION
1,Sistema,2QEK,SALTO II,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,ENDG,AGUA,2014-06-25,OPERACION
2,Sistema,2QRL,LA REBUSCA,HIDRAULICA,NO DESPACHADO CENTRALMENTE,GEN. DISTRIBUIDA,HZEG,AGUA,2014-07-24,OPERACION
3,Sistema,2QV2,BAJO TULUA,HIDRAULICA,NO DESPACHADO CENTRALMENTE,NORMAL,EPSG,AGUA,2015-01-30,OPERACION
4,Sistema,2R22,LAGUNETA,HIDRAULICA,NO DESPACHADO CENTRALMENTE,NORMAL,ENDG,AGUA,2014-12-17,OPERACION

In [ ]:
# Total plantas y mapeo de plantas en el despacho - plantas sinergox
df_Plantas = df_Aux[['Planta']]
df_Plantas=df_Plantas.merge(df_Rec, how='left', left_on='Planta', right_on='Values_Name')[['Planta','Values_Type','Values_Disp']]
df_Plantas
# df_Plantas_missing = df_Plantas[df_Plantas['Values_Type'].isna()]
# df_Plantas_missing

          Planta Values_Type                 Values_Disp
0    AGUA FRESCA  HIDRAULICA  NO DESPACHADO CENTRALMENTE
1          ALBAN  HIDRAULICA     DESPACHADO CENTRALMENTE
2     ALEJANDRIA  HIDRAULICA  NO DESPACHADO CENTRALMENTE
3     ALTO TULUA  HIDRAULICA  NO DESPACHADO CENTRALMENTE
4         AMAIME  HIDRAULICA  NO DESPACHADO CENTRALMENTE
..           ...         ...                         ...
386    ZIPAEMG 2     TERMICA     DESPACHADO CENTRALMENTE
387    ZIPAEMG 3     TERMICA     DESPACHADO CENTRALMENTE
388    ZIPAEMG 4     TERMICA     DESPACHADO CENTRALMENTE
389    ZIPAEMG 5     TERMICA     DESPACHADO CENTRALMENTE
390        Total         NaN                         NaN

[391 rows x 3 columns]

In [ ]:
# Plantas térmicas con despacho central
df_Termica=df_Plantas[(df_Plantas['Values_Type']=='TERMICA') & (df_Plantas['Values_Disp']=='DESPACHADO CENTRALMENTE')]
df_Termica=df_Termica.sort_values(by='Planta')
df_Termica.to_csv('PlantasTérmicas.csv')
df_Termica

                 Planta Values_Type              Values_Disp
62       BARRANQUILLA 3     TERMICA  DESPACHADO CENTRALMENTE
63       BARRANQUILLA 4     TERMICA  DESPACHADO CENTRALMENTE
86          CARTAGENA 1     TERMICA  DESPACHADO CENTRALMENTE
87          CARTAGENA 2     TERMICA  DESPACHADO CENTRALMENTE
88          CARTAGENA 3     TERMICA  DESPACHADO CENTRALMENTE
132         FLORES 4 CC     TERMICA  DESPACHADO CENTRALMENTE
133         FLORES I CC     TERMICA  DESPACHADO CENTRALMENTE
162           GECELCA 3     TERMICA  DESPACHADO CENTRALMENTE
163          GECELCA 32     TERMICA  DESPACHADO CENTRALMENTE
171           GUAJIRA 1     TERMICA  DESPACHADO CENTRALMENTE
172           GUAJIRA 2     TERMICA  DESPACHADO CENTRALMENTE
228      MERILECTRICA 1     TERMICA  DESPACHADO CENTRALMENTE
254             PAIPA 1     TERMICA  DESPACHADO CENTRALMENTE
255             PAIPA 2     TERMICA  DESPACHADO CENTRALMENTE
256             PAIPA 3     TERMICA  DESPACHADO CENTRALMENTE
257             PAIPA 4     TERMICA  DESPACHADO CENTRALMENTE
287      PROELECTRICA 1     TERMICA  DESPACHADO CENTRALMENTE
288      PROELECTRICA 2     TERMICA  DESPACHADO CENTRALMENTE
343          TASAJERO 1     TERMICA  DESPACHADO CENTRALMENTE
344          TASAJERO 2     TERMICA  DESPACHADO CENTRALMENTE
345           TEBSAB CC     TERMICA  DESPACHADO CENTRALMENTE
352  TERMOCANDELARIA CC     TERMICA  DESPACHADO CENTRALMENTE
354   TERMOCARIBE III 1     TERMICA  DESPACHADO CENTRALMENTE
355      TERMOCENTRO CC     TERMICA  DESPACHADO CENTRALMENTE
356       TERMODORADA 1     TERMICA  DESPACHADO CENTRALMENTE
357      TERMOEMCALI CC     TERMICA  DESPACHADO CENTRALMENTE
361          TERMONORTE     TERMICA  DESPACHADO CENTRALMENTE
363      TERMOSIERRA CC     TERMICA  DESPACHADO CENTRALMENTE
365       TERMOVALLE CC     TERMICA  DESPACHADO CENTRALMENTE
366        TERMOYOPAL 1     TERMICA  DESPACHADO CENTRALMENTE
367        TERMOYOPAL 2     TERMICA  DESPACHADO CENTRALMENTE
368       TERMOYOPAL G3     TERMICA  DESPACHADO CENTRALMENTE
369       TERMOYOPAL G4     TERMICA  DESPACHADO CENTRALMENTE
370       TERMOYOPAL G5     TERMICA  DESPACHADO CENTRALMENTE
371            TESORITO     TERMICA  DESPACHADO CENTRALMENTE
386           ZIPAEMG 2     TERMICA  DESPACHADO CENTRALMENTE
387           ZIPAEMG 3     TERMICA  DESPACHADO CENTRALMENTE
388           ZIPAEMG 4     TERMICA  DESPACHADO CENTRALMENTE
389           ZIPAEMG 5     TERMICA  DESPACHADO CENTRALMENTE

In [ ]:
# Plantas hidráulicas con despacho central
df_Hidro=df_Plantas[(df_Plantas['Values_Type']=='HIDRAULICA') & (df_Plantas['Values_Disp']=='DESPACHADO CENTRALMENTE')]
df_Hidro=df_Hidro.sort_values(by='Planta')
df_Hidro.to_csv('PlantasHidro.csv')
df_Hidro

,Planta,Values_Name,Values_Type,Values_Disp,Values_RecType,Values_State
811,ALBAN,ALBAN,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
886,AMOYA LA ESPERANZA,AMOYA LA ESPERANZA,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
831,BETANIA,BETANIA,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
838,CALIMA,CALIMA,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
837,CARLOS LLERAS,CARLOS LLERAS,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO AGUA ESPECIAL,OPERACION
832,CHIVOR,CHIVOR,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
849,CUCUANA,CUCUANA,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
851,DARIO VALENCIA SAMPER,DARIO VALENCIA SAMPER,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
919,EL QUIMBO,EL QUIMBO,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
864,ESCUELA DE MINAS,ESCUELA DE MINAS,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
853,ESMERALDA,ESMERALDA,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
860,GUATAPE,GUATAPE,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
861,GUATRON,GUATRON,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
862,GUAVIO,GUAVIO,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
893,ITUANGO,ITUANGO,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
875,JAGUAS,JAGUAS,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
880,LA TASAJERA,LA TASAJERA,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
865,MIEL I,MIEL I,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
894,PAGUA,PAGUA,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
899,PLAYAS,PLAYAS,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
907,PORCE II,PORCE II,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
908,PORCE III,PORCE III,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
910,PRADO,PRADO,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
1,SALTO II,SALTO II,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
938,SALVAJINA,SALVAJINA,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
941,SAN CARLOS,SAN CARLOS,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
942,SAN FRANCISCO,SAN FRANCISCO,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
939,SAN MIGUEL,SAN MIGUEL,HIDRAULICA,DESPACHADO CENTRALMENTE,FILO DE AGUA,OPERACION
945,SOGAMOSO,SOGAMOSO,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
982,URRA,URRA,HIDRAULICA,DESPACHADO CENTRALMENTE,NORMAL,OPERACION

In [19]:
# Plantas Eólicas y Solares con despacho central
df_Otros=df_Plantas[(~df_Plantas['Values_Type'].isin(['HIDRAULICA','TERMICA'])) & (df_Plantas['Values_Disp']=='DESPACHADO CENTRALMENTE')]
df_Otros=df_Otros.sort_values(by='Planta')
df_Otros.to_csv('PlantasOtros.csv')
df_Otros

,Planta,Values_Name,Values_Type,Values_Disp,Values_RecType,Values_State
356,CARACOLI I,CARACOLI I,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
852,EL PASO,EL PASO,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
284,FUNDACION,FUNDACION,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
863,GUAYEPO,GUAYEPO,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
881,LA MATA,LA MATA,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
131,LATAM SOLAR LA LOMA,LATAM SOLAR LA LOMA,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
377,PARQUE SOLAR LA UNION,PARQUE SOLAR LA UNION,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
966,PARQUE SOLAR TEPUY,PARQUE SOLAR TEPUY,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
364,PORTON DEL SOL,PORTON DEL SOL,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
363,SUNNORTE,SUNNORTE,SOLAR,DESPACHADO CENTRALMENTE,NORMAL,OPERACION
816,NaN,FUTURA - PARQUE ALPHA,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
817,NaN,FUTURA - APOTOLORRU,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
822,NaN,FUTURA - PARQUE BETA,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
829,NaN,FUTURA - CASA ELECTRICA,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS

In [ ]:
# Total plantas y mapeo de plantas sinergox - plantas en el despacho
df_Plantas = df_Aux[['Planta']]
df_Plantas=df_Rec.merge(df_Plantas, how='left', left_on='Values_Name', right_on='Planta')[['Planta','Values_Name','Values_Type','Values_Disp','Values_RecType','Values_State']]
df_Plantas
df_Plantas_missing = df_Plantas[df_Plantas['Planta'].isna()]
df_Plantas_missing=df_Plantas_missing[(df_Plantas_missing['Values_RecType']!='AUTOG PEQ. ESCALA')]
df_Plantas_missing

,Planta,Values_Name,Values_Type,Values_Disp,Values_RecType,Values_State
9,NaN,AUTOG ARGOS TOLUVIEJO,TERMICA,NO DESPACHADO CENTRALMENTE,AUTOGENERADOR,PRUEBAS
44,NaN,TERMOCAPACHOS 1,TERMICA,NO DESPACHADO CENTRALMENTE,NORMAL,OPERACION
636,NaN,BUENAVISTA,SOLAR,NO DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
667,NaN,SOL DEL MAR II,SOLAR,NO DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
718,NaN,LA MARTINA,SOLAR,NO DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
756,NaN,AUTOG LOS POCITOS 1,TERMICA,NO DESPACHADO CENTRALMENTE,AUTOGENERADOR,OPERACION
816,NaN,FUTURA - PARQUE ALPHA,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
817,NaN,FUTURA - APOTOLORRU,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
822,NaN,FUTURA - PARQUE BETA,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
829,NaN,FUTURA - CASA ELECTRICA,EOLICA,DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
835,NaN,NIMA II,HIDRAULICA,NO DESPACHADO CENTRALMENTE,FILO DE AGUA,PRUEBAS
918,NaN,FUTURA - PTAR 1,TERMICA,NO DESPACHADO CENTRALMENTE,NORMAL,PRUEBAS
954,NaN,TERMOCANDELARIA CC 1,TERMICA,DESPACHADO CENTRALMENTE,CICLO COMBINADO,OPERACION
955,NaN,TERMOCANDELARIA CC 2,TERMICA,DESPACHADO CENTRALMENTE,CICLO COMBINADO,OPERACION